# Generated by Django 5.0.3 on 2024-04-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
